### ISSUE TITLE
Request: Get rid of the files "tileset.entities.png"

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/solarus#1074]
Get rid of the files "tileset.entities.png". You may agree or not, and if not, just close the issue.

Destructible entities, doors and blocks already use sprites and don't need to appear in files "tileset.entities.png". Ground animation effects, like the moving grass and the moving shallow water, should be doable with custom grounds when these are coded in future versions of the engine, so they will not need to appear in that file either. Bomb-flowers and wooden-signs are too especific and probably should be done with custom entities (that can be carried). So I think it would be a good idea to get rid of that type of tileset files, or at least make them optional and get rid of the warning already mentioned in https://github.com/solarus-games/solarus/pull/893

**Comment by Diarandor** [comment]
The sprites for built-in grounds and custom grounds could be in a specific folder, maybe "sprites/grounds/"

**Comment by christopho** [comment]
Tileset-dependent sprites are useful sometimes.

It is true that the tileset.entities.png images that we currently have in most quests contain a lot sprites that should not be here (because they actually are the same for all tilesets). But doors and blocks are still tileset dependent.

In 1.6 we will make the file optional and remove the warning.
