### ISSUE TITLE
Random movement gives the same path for all entities on Mac OS

### ISSUE THREAD

**Issue by christopho** [solarus-games/solarus#1083]
See https://bitbucket.org/zeldaforce/zelda-lafd/issues/31/vegas-movement
or https://youtu.be/JjwY2QJeIzY?t=12m34s

It looks like the random numbers returned by Random::get_number() are the same when the function is called in the same second. Maybe the thread_local storage specifier is not working on Mac? @Morwenn, any clue?

@vlag, can you check if replacing thread_local by static at lines 78 and 79 of src/lowlevel/Random.cpp solves the problem?

**Comment by Morwenn** [comment]
The pseudo-random number engine is initialized with `std::time(nullptr)` in each thread, so if several threads initialize their engine at the same time, they will produce the same batch of values afterwards. since pseudo-random number engines are deterministic. `std::time(nullptr)` is actually a poor seed and [`std::random_device`](http://en.cppreference.com/w/cpp/numeric/random/random_device) should be used instead to initialize the pseudo-random numbers engine with an actual random value.

I initially used `std::time(nullptr)` because `std::random_device` does not work with MinGW: it always produces the same values at every execution. A first simple solution would be to use `std::random_device` everywhere and keep `std::time(nullptr)` for MinGW only, but you should probably investigate to find a better way to always have an actual random value. Looking at [how Boost implements its own `random_device`](https://github.com/boostorg/random/blob/develop/src/random_device.cpp) might help to see how it finds true random numbers on Windows. It looks fairly complicated.

**Comment by Morwenn** [comment]
Looks like `std::time` returns its result in seconds most of the time. No wonder it makes a poor seed. It's not unexpected for two threads to launch at the same second. Moreover, the standard doesn't make many assumptions about when a `thread_local` variable is initialized:

> A variable with thread storage duration shall be initialized before its first odr-use (3.2) and, if constructed, shall be destroyed on thread exit.

Basically, an implementation could be free to initialize any `thread_local` variable when the thread launches, which might happen with some implementations but not with other ones. I don't know the specifics, so I can't tell which implementation does what, but at this points it looks obvious that several pseudo-random number generators are initialized at the same second, making them use the same `std::time` seed.

**Comment by christopho** [comment]
There is only one thread in Solarus (at least for now). So the bug is not that several threads produce the same sequence of numbers, it is that several successive calls to Random::get_number() from the same thread during the same second give the same result. Just like if the seed from the previous call was simply forgotten.

So in other words, everything behaves like if the thread_local specifier was not there. The seed would then be a regular local variable, initialized to std::time(nullptr) at every call. I tried to remove thread_local and I reproduce the exact same bug.

I suspect that the compiler used to build Solarus on Mac OS X does not support thread_local and just ignores it. @vlag will tell us :)

If this is the explanation, then an easy fix is to replace thread_local by static, which is okay as long as there is only one thread.

**Comment by Morwenn** [comment]
Oh, if there's only a single thread, you can indeed just try to turn the `thread_local` into a `static`, it should be enough ^^

IIRC there was a `__thread` thingy that should be equivalent to `thread_local`, but it only works with PODs and I don't think there is any guarantee about the pseudo-random number generators to be PODs. `static` seems to be the best way to deal with the problem right now.

**Comment by christopho** [comment]
Should be fixed now. If anyone can confirm it could be great.

**Comment by Diarandor** [comment]
> Should be fixed now. If anyone can confirm it could be great.

Maybe we should ask for this in the forums.

**Comment by vlag** [comment]
I don't often turn on my computer these days but I'll check tonight if I'll remember ;)

**Comment by christopho** [comment]
@vlag Any news?
